# Generated by Django 5.2.5 on 2025-08-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='cedula',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
