# Generated by Django 5.2.5 on 2025-08-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_telefono_usuario_cedula_remove_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceco',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tiposoporte',
            name='descripcion',
        ),
    ]
