# Generated by Django 5.2.5 on 2025-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soporte',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='usuario',
        ),
        migrations.AddField(
            model_name='soporte',
            name='nombre',
            field=models.CharField(default='Soporte', max_length=100),
        ),
        migrations.AlterField(
            model_name='ceco',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
