# Generated by Django 5.2.5 on 2025-08-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_remove_soporte_activo_remove_soporte_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='atendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atendidos', to='app2.soporte'),
        ),
    ]
