# Generated by Django 5.2.5 on 2025-08-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_alter_ticket_atendido_por'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ceco',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ceco',
            new_name='area',
        ),
    ]
