# Generated by Django 5.2.5 on 2025-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_rename_ceco_area_rename_ceco_ticket_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_problema',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('sistema', 'Sistema'), ('hardware', 'Hardware')], default='usuario', max_length=20),
        ),
    ]
